#!/bin/bash

artifact=apache-ant
version=1.9.7
name=${artifact}-${version}
fn=${name}-bin.zip

dl=download/$fn

if [[ ! -f "$dl" ]]; then
  wget -O $dl http://apache.cs.utah.edu/ant/binaries/$fn
  if [[ ! -f "$dl"  ]]; then
    echo "$fn download failed"
    exit 1
  fi
fi
addition="--template-value path_name=$name --template-value my_path_file=ant.sh --template-value my_home=ANT_HOME --template-scripts --after-install scripts/setpath "
. common


