#!/bin/bash

t=tmp/${fn}_work

if [[ -d "$t" ]];then
  rm -rf $t
fi
mkdir $t -p

# 解压
if [ "${fn##*.}" == "zip" ];then
  unzip download/$fn -d $t
fi


if [ "${fn#*.}" == "tar.gz" ];then
  tar -xvf download/$fn -C $t
else
  
  if [ "${fn##*.}" == "gz" ];then
     tar -xvf download/$fn -C $t
  fi
fi


name_prefix='ddb-'
install=/usr/local/opt
output=build

fpm -f -s dir -t rpm --verbose --epoch 0 \
 -p $output \
 -n $name_prefix$name \
 --url "https://info.evan.io" \
 -m 'evan' \
 --license 'MIT' \
 --category 'Development/Languages' \
 --description "$name" \
 --rpm-auto-add-directories \
 --no-rpm-sign $addition \
 --workdir tmp \
 --prefix $install \
 -C $t \
 $name

