#!/bin/bash

artifact=elasticsearch
version=2.3.5
name=${artifact}-${version}
fn=${name}.zip

dl=download/$fn

if [[ ! -f "$dl" ]]; then
  wget -O $dl https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/zip/$artifact/$version/$fn
  if [[ ! -f "$dl"  ]]; then
    echo "$fn download failed"
    exit 1
  fi
fi

. common


