#!/bin/bash

artifact=gradle
version=2.14.1
name=${artifact}-${version}
fn=${name}-bin.zip

dl=download/$fn
if [[ ! -f "$dl" ]]; then
  wget -O $dl https://services.gradle.org/distributions/$fn
  if [[ ! -f "$dl"  ]]; then
    echo "$fn download failed"
    exit 1
  fi
fi


addition="--template-value path_name=$name --template-value my_path_file=gradle.sh --template-value my_home=GRADLE_HOME --template-scripts --after-install scripts/setpath "
. common


