#!/bin/bash

artifact=jdk
version=8u102
name=jdk1.8.0_102
fn=jdk-8u102-linux-x64.tar.gz

dl=download/$fn

if [[ ! -f "$dl" ]]; then
  wget -O $dl --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.tar.gz
  if [[ ! -f "$dl"  ]]; then
    echo "$fn download failed"
    exit 1
  fi
fi


addition="--template-value path_name=$name --template-value my_path_file=java.sh --template-value my_home=JAVA_HOME --template-scripts --after-install scripts/setpath "

. common


