#!/bin/bash

artifact=kibana
version=4.5.4
name=${artifact}-${version}
fn=${name}-linux-x64.tar.gz

https://download.elastic.co/kibana/kibana/kibana-4.5.4-linux-x64.tar.gz

dl=download/$fn
if [[ ! -f "$dl" ]]; then
  wget -O $dl https://download.elastic.co/$artifact/$artifact/$fn
  if [[ ! -f "$dl"  ]]; then
    echo "$fn download failed"
    exit 1
  fi
fi

. common


