#!/bin/bash

artifact=mysql
version=5.6.32
name=${artifact}-${version}
fn=${name}.tar.gz

dl=download/$fn

if [[ ! -f "$dl" ]]; then
  wget -O $dl http://cdn.mysql.com//Downloads/MySQL-5.6/$fn
  if [[ ! -f "$dl"  ]]; then
    echo "$fn download failed"
    exit 1
  fi
fi


sudo yum install -y gcc-c++ cmake bison-devel  ncurses-devel

dir=`pwd`
t=tmp/${fn}_work
d=tmp/${fn}_bin
mkdir -p $t
mkdir -p $d

tmp_install=$dir/tmp/${fn}_install
#rm -rf $tmp_install
mkdir -p $tmp_install
## Build redis
if [ 'x' != 'b' ]; then
tar zxvf $dl -C $t
cd $t/$name

cmake \
-DCMAKE_INSTALL_PREFIX=$tmp_install/$name \
-DMYSQL_DATADIR=/data/mysql/data \
-DSYSCONFDIR=/etc \
-DWITH_MYISAM_STORAGE_ENGINE=1 \
-DWITH_INNOBASE_STORAGE_ENGINE=1 \
-DWITH_MEMORY_STORAGE_ENGINE=1 \
-DWITH_READLINE=1 \
-DMYSQL_UNIX_ADDR=/var/lib/mysql/mysql.sock \
-DMYSQL_TCP_PORT=3306 \
-DENABLED_LOCAL_INFILE=1 \
-DWITH_PARTITION_STORAGE_ENGINE=1 \
-DEXTRA_CHARSETS=all \
-DDEFAULT_CHARSET=utf8 \
-DDEFAULT_COLLATION=utf8_general_ci

make && make install

cd -
fi


name_prefix='ddb-'
install=/usr/local/opt
output=build
#exit

fpm -f -s dir -t rpm --verbose --epoch 0 \
 -p $output \
 -n $name_prefix$name \
 --url "https://info.evan.io" \
 -m 'evan' \
 --license 'MIT' \
 --category 'Development/Languages' \
 --description "$name" \
 --rpm-auto-add-directories \
 --rpm-init scripts/init.d/mysqld \
 --no-rpm-sign $addition \
 --workdir tmp \
 --prefix $install \
 -C $tmp_install \
 $name

#. common


