#!/bin/bash

artifact=wildfly
version=9.0.2.Final
name=${artifact}-${version}
fn=${name}.zip

dl=download/$fn

if [[ ! -f "$dl" ]]; then
  wget -O $dl http://download.jboss.org/wildfly/9.0.2.Final/$fn
  if [[ ! -f "$dl"  ]]; then
    echo "$fn download failed"
    exit 1
  fi
fi

. common


