#!/bin/bash

artifact=zookeeper
version=3.4.6
name=${artifact}-${version}
fn=${name}.tar.gz

dl=download/$fn

if [[ ! -f "$dl" ]]; then
  wget -O $dl http://apache.claz.org/zookeeper/$name/$fn
  if [[ ! -f "$dl"  ]]; then
    echo "$fn download failed"
    exit 1
  fi
fi

. common


